### PR TITLE
Sync Develop

### PR DESCRIPTION
**Pull request by betweenbrain**
Master seems to be out of sync with develop, this PR rectifies that  and a the `Parse error: syntax error, unexpected T_ELSEIF`

### CODE REVIEW

**Comment by wilsonge** [comment]
Oops my bad. looks like I added that commit the other day into master rather than development :/ Can we make develop branch the default one please?

**Comment by betweenbrain** [comment]
Done.

**Comment by betweenbrain** [comment]
I'll close this PR then. Can you apply that commit to develop instead, and that way, we can sync everything up.

**Comment by wilsonge** [comment]
yeah of course :)

**Comment by wilsonge** [comment]
All done

**Pull request closed without merging**
