### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by betweenbrain**

### CODE REVIEW

**Comment by wilsonge** [comment]
We need to create an issue for this for Joomla Core

**Comment by betweenbrain** [comment]
Yes we do :smile: It's being created now.

**Comment by betweenbrain** [comment]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=32166

**Comment by betweenbrain** [comment]
PR at https://github.com/joomla/joomla-cms/pull/2133

**Pull request merged**
