### PR TITLE
Allow Joomla Naming Convention

### PR DESCRIPTION
**Pull request by AlexBachmann**
Allow Helper Classes to be named camel case, while module names are separated by an underscore.

### CODE REVIEW

**Comment by betweenbrain** [comment]
And, thanks!

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/master/modules/mod_articles_popular/helper.php

So the module name is mod_articles_popular but the helper name doesn't have that extra _ in - ModArticlesPopularHelper

**Comment by AlexBachmann** [comment]
Hi Matt,

If you have a module, which name is a composite of two parts, it is the Joomla convention to call the module mod_part1_part2 and the Helper class is named ModPart1Part2Helper. You can see this convention used in mod_articles_latest, mod_random_image and other modules of that sort.

The component translates the module name directly into the helper classname. Hence it looks for helper classes like ModPart1_part2Helper instead of ModPart1Part2Helper. This causes the extension to fail. I think this is an easy problem to fix. I would suggest to check if the first classname exists and if it does not exists, it checks for the other classname.

Best regards,
Alex

**Comment by betweenbrain** [comment]
Hi Alexander ,

My sincerest apologies for not responding sooner. Life has been a bit busy lately. I spent some time looking at your contribution this morning, and it is something that needs correcting. Thank you. 

Instead of basing the check on `if(!class_exists($class))` what do you think of doing something like

```
    if (strpos($module, '_')) {
        $parts = explode('_', $module);
        $class = 'mod';
        foreach ($parts as $part) {
            $class .= ucfirst($part);
        }
        $class .= 'Helper';
    } else {
        $class = 'mod' . ucfirst($module) . 'Helper';
    }
```

**Comment by AlexBachmann** [comment]
Hey Matt. Yes, this seems to be a more cleaner approach.

**Comment by betweenbrain** [comment]
Great. Would you be interested in revising your PR to reflect this? I want to be sure that you get credit :smile:

**Comment by AlexBachmann** [comment]
Done.

**Comment by betweenbrain** [comment]
Excellent, thanks! I'll get this merged as soon as I can.

**Comment by betweenbrain** [comment]
Merged via d800b5859271d16a5b1a825840c0a2d03570c517 Thanks Alexander!

**Pull request closed without merging**
