### PR TITLE
added script.php

### PR DESCRIPTION
**Pull request by C-Lodder**
- Added the script to remove the menu item on install.
- Uses $db->query() instead of $db->execute() as (if I rightly remember) execute won't work with J1.5

Tested and working :+1:

### CODE REVIEW

**Comment by wilsonge** [comment]
I'm pretty sure JDatabaseQuery doesn't exist in Joomla 1.5. @betweenbrain you're the expert there?

**Comment by C-Lodder** [comment]
In J1.5 I don't think `$query = $db->getQuery(true);` was used. But also, I don't think 1.5 supported the `<scriptfile>` tag so wouldn't this component need to be separated for 1.5 and 2.5?

**Comment by wilsonge** [comment]
It would just mean the script would only remove the menu item in Joomla 2.5 and not 1.5.... but that seems to have been the case since ever. So not sure how big a deal it is

**Comment by C-Lodder** [comment]
What's happening with this? 
Have any decisions been made as to how 1.5 and 2.5 can both be catered for?

**Pull request merged**
